project_id = "yvorffsdardyoyfanpgh"

[functions.cleanup-unpaid-orders]
verify_jwt = false

[functions.line-auth]
verify_jwt = false

[functions.line-notify]
verify_jwt = false

[functions.line-webhook]
verify_jwt = false

[functions.generate-qr]
verify_jwt = false

[functions.verify-slip]
verify_jwt = false

[functions.send-payment-reminder]
verify_jwt = false

[functions.line-push-message]
verify_jwt = false
